-module(ssh_sftp_sup).
-behaviour(supervisor).

-export([start_link/0, start_child/2, list_for_conn/1, rpc_open/1]).
-export([init/1]).

%% @doc Start the SFTP session pool supervisor (simple_one_for_one).
start_link() ->
    supervisor:start_link({local, ?MODULE}, ?MODULE, []).

%% @doc Start a new SFTP session worker.
%% ConnId identifies the parent connection; SshRef is the ssh connection reference.
%% Returns {ok, SftpId} | {error, Reason}.
start_child(ConnId, SshRef) ->
    case supervisor:start_child(?MODULE, [ConnId, SshRef]) of
        {ok, Pid} ->
            %% Retrieve the sftp_id generated by the session worker
            SftpId = ssh_sftp_session:get_id(Pid),
            ets:insert(sftp_index, {SftpId, Pid}),
            {ok, SftpId};
        {error, Reason} ->
            {error, Reason}
    end.

%% @doc List all SFTP sessions for a given connection.
list_for_conn(ConnId) ->
    [Pid || {_, Pid, _, _} <- supervisor:which_children(?MODULE),
            ssh_sftp_session:conn_id(Pid) =:= ConnId].

%% @doc RPC handler for sftp.open
rpc_open(#{<<"conn_id">> := ConnId}) ->
    case find_conn_worker(ConnId) of
        {ok, Pid} ->
            SshRef = ssh_conn_worker:get_ssh_ref(Pid),
            start_child(ConnId, SshRef);
        {error, not_found} ->
            {error, conn_not_found}
    end.

%% @doc simple_one_for_one, intensity 20/60s, temporary workers.
init([]) ->
    SupFlags = #{
        strategy => simple_one_for_one,
        intensity => 20,
        period => 60
    },
    ChildSpec = #{
        id => ssh_sftp_session,
        start => {ssh_sftp_session, start_link, []},
        restart => temporary,
        shutdown => 5000,
        type => worker,
        modules => [ssh_sftp_session]
    },
    {ok, {SupFlags, [ChildSpec]}}.

find_conn_worker(ConnId) ->
    case [Pid || Pid <- ssh_conn_sup:all_workers(),
                 ssh_conn_worker:conn_id(Pid) =:= ConnId] of
        [Pid | _] -> {ok, Pid};
        [] -> {error, not_found}
    end.
